# Software Engineering - Independent Hugo Site Configuration
baseURL: "/software-engineering/"
title: "Software Engineering | Sakthi Priyan"
theme: "continuum"
languageCode: "en-us"
defaultContentLanguage: "en"

params:
  description: "Technical insights, development tools, and engineering best practices for software professionals"
  author: "Sakthi Priyan"
  siteType: "software-engineering"

markup:
  goldmark:
    renderer:
      unsafe: true

# Menu configuration for software-engineering site
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 5
    - name: "Blogs"
      url: "/blogs/"
      weight: 10
    - name: "Videos"
      url: "/videos/"
      weight: 20
    - name: "Slides"
      url: "/slides/"
      weight: 30
    - name: "Tools"
      url: "/tools/"
      weight: 40
    - name: "Books"
      url: "/books/"
      weight: 45
    - name: "Tags"
      url: "/tags/"
      weight: 50

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

outputs:
  home: ["HTML", "RSS"]
  page: ["HTML"]
  section: ["HTML", "RSS"]

# Taxonomies
taxonomies:
  tag: "tags"
  category: "categories"
